name = "voidmark-capes"
main = "worker.js"
compatibility_date = "2026-09-01"

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = true

[vars]
PAYPAL = "your-paypal@email.com"
PRICE = "$1"
TITLE = "VOIDMARK Capes"

[[r2_buckets]]
binding = "CAPES"
bucket_name = "voidmark-capes"
