name = "voidmark-capes"
main = "worker.js"
compatibility_date = "2026-09-01"

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = true

[vars]
TITLE = "VOIDMARK Capes"
MOD_GITHUB = "Shora/voidmark"
MOD_GITHUB_BRANCH = "main"
MOD_GITHUB_PATH = "web/public/mod"

[[r2_buckets]]
binding = "CAPES"
bucket_name = "voidmark-capes"
